POST http://localhost:3001/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyZTZiMDU4LWE0MjctNGQwNy1hMzllLWM4NDk0MjRhN2YzMSIsIm5vbWUiOiJOb2N0YSIsInBlcm1BdGVuZGltZW50byI6dHJ1ZSwicGVybUNhZGFzdHJvIjp0cnVlLCJwZXJtQWRtaW4iOnRydWUsImlhdCI6MTc2NDQ2Mjc1NiwiZXhwIjoxNzY0NTQ5MTU2fQ.NFQ4wmsHd6Z5VJcN8khxOoq9j6aN6VBL3dKN0HCWcxw
  
{
  "nome": "Leticia",
  "email": "leticia@gmail.com",
  "email": "telefoneTeste",
  "matricula": 1
}

###

POST http://localhost:3001/users/login
Content-Type: application/json

{
  "email": "nocta.smd@teste.com",
  "senha": "nocta123"
}

###

PUT http://localhost:3001/users/b7c5e4bd-9ac2-4d58-a0b9-4c7bbc908a31
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI3YzVlNGJkLTlhYzItNGQ1OC1hMGI5LTRjN2JiYzkwOGEzMSIsIm5vbWUiOiJMZXRpY2lhIiwicGVybUF0ZW5kaW1lbnRvIjp0cnVlLCJwZXJtQ2FkYXN0cm8iOmZhbHNlLCJwZXJtQWRtaW4iOmZhbHNlLCJpYXQiOjE3NjQ1MTIyMDcsImV4cCI6MTc2NDU5ODYwN30.Bnm-G3MUT8T1vkf2KVctXL_uhYj4em_tx_NGFsP_o_M

{
  "nome": "Letícia",
  "telefone": "1",
  "fotoUrl": "teste",
  "email": "leticia@gmail.com",
  "senha": "leticia1234"
}

###
PATCH  http://localhost:3001/users/primeiro-acesso
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI3YzVlNGJkLTlhYzItNGQ1OC1hMGI5LTRjN2JiYzkwOGEzMSIsIm5vbWUiOiJMZXRpY2lhIiwicGVybUF0ZW5kaW1lbnRvIjp0cnVlLCJwZXJtQ2FkYXN0cm8iOmZhbHNlLCJwZXJtQWRtaW4iOmZhbHNlLCJpYXQiOjE3NjQ1MTE5NTIsImV4cCI6MTc2NDU5ODM1Mn0.RPRCoU_PAYe0CPtzYmy-HUNbVJbAEDYUO98SbMUK738

{
  "telefone": "2",
  "fotoUrl": "teste2",
  "senha": "leticia123"
}

###
GET http://localhost:3001/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjJkMDZhLTUyNjItNGZkNC05NjEyLWRiMWY1NmIwMTljOCIsIm5vbWUiOiJWaW5hIENyYXF1ZSBkZSBCb2xhIiwicGVybUF0ZW5kaW1lbnRvIjp0cnVlLCJwZXJtQ2FkYXN0cm8iOmZhbHNlLCJwZXJtQWRtaW4iOmZhbHNlLCJpYXQiOjE3NjQ1OTQ5MTMsImV4cCI6MTc2NTE5OTcxM30._bT3wXJrUwIKY3suJNKcq-N1at3ZPelZjL4peEbMNDo